### ISSUE TITLE
GitHub Actions Config for macOS (needs ICU)

### ISSUE THREAD

**Issue by pjones** [pjones/addy#3]
Addy works on macOS, but needs ICU libraries for the `text-icu` package to build.  I don't know how to get this working on macOS.

```
Failed to build text-icu-0.7.0.1. The failure occurred during the configure
step.
Build log ( logs/text-icu-0.7.0.1 ):
cabal: Failed to build text-icu-0.7.0.1 (which is required by test:test from
addy-0.1.0.1). See the build log above for details.
Configuring library for text-icu-0.7.0.1..
cabal-3.2.0.0: Missing dependencies on foreign libraries:
* Missing (or bad) C libraries: icuuc, icui18n, icudata
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
the library files do exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

**Comment by pjones** [comment]
I removed this from the CI config because it didn't work:

```yaml
      - name: Install macOS Dependencies
        if: matrix.os == 'macOS-latest'
        run: |
          echo 'LDFLAGS="-L/usr/local/opt/icu4c/lib"' >> $GITHUB_ENV
          echo 'CPPFLAGS="-I/usr/local/opt/icu4c/include"' >> $GITHUB_ENV
          echo 'PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"' >> $GITHUB_ENV
```
